import { Inter_Tight, Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const inter_tight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata = {
  title: "Fortune Sealing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${inter_tight.variable} ${poppins.variable}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
